# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1080, 720)
        Widget.setMinimumSize(QtCore.QSize(1080, 720))
        Widget.setStyleSheet("\n"
                             "background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(0, -20, 381, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/AI Bot - Copy.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(400, 20, 661, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/Untitled_design__1_-removebg-preview (1).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(410, 600, 201, 141))
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setStyleSheet("border-image: url(:/Downloads/Untitled_design__3_-removebg-preview.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 600, 201, 141))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("border-image: url(:/Downloads/Untitled_design__2_-removebg-preview (4).png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(400, 110, 661, 501))
        self.label_3.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border-style:solid;\n"
                                   "border-width : 1px 1px 1px 1px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
